export enum QueryKeysLand {
  GET_SELF = 'GET_SELF',
  GET_USER_BY_NICKNAME = 'GET_USER_BY_NICKNAME',
  SEARCH_USERS = 'SEARCH_USERS',
  GET_TAGS = 'GET_TAGS',
  GET_ALL_POSTS = 'GET_ALL_POSTS',
  GET_POPULAR_POSTS = 'GET_POPULAR_POSTS'
}
